export const FADE_IN_ANIMATION_SETTINGS = {
  initial: { opacity: 0 },
  animate: { opacity: 1 },
  transition: { duration: 0.2 },
};

export const FADE_DOWN_ANIMATION_VARIANTS = {
  hidden: { opacity: 0, y: -10 },
  show: { opacity: 1, y: 0, transition: { type: "spring" } },
};

export const FADE_UP_ANIMATION_VARIANTS = {
  hidden: { opacity: 0, y: 10 },
  show: { opacity: 1, y: 0, transition: { type: "spring" } },
};

export enum INDUSTRIES {
  "Aerospace",
  "Agriculture",
  "Biotechnology",
  "Chemicals",
  "Commerce",
  "Construction",
  "Consulting",
  "Distribution",
  "Economics",
  "Education",
  "Electronics",
  "Energy",
  "Engineering",
  "Entertainment",
  "Fast-moving consumer goods",
  "Financial services",
  "Food",
  "Forestry",
  "Healthcare",
  "Heavy industry",
  "Hospitality",
  "Human Resources",
  "Insurance",
  "Investment",
  "Logistics",
  "Manufacturing",
  "Marketing",
  "Media",
  "Metalworking",
  "Mining",
  "Music",
  "News / Media",
  "Pharmaceutical",
  "Public administration",
  "Real Estate",
  "Recruitment",
  "Retail",
  "Robotics",
  "Sales",
  "Technology",
  "Telecommunication",
  "Trade",
  "Transport",
}
